services:
  ffmpeg:
    image: jrottenberg/ffmpeg:5.1-ubuntu
    container_name: ffmpeg
    working_dir: /data
    volumes:
      - ./data:/data
    command: tail -f /dev/null
    networks:
      - n8n_shared